export interface Account {
  name: string;
  domain: string;
  industry: string;
  country: string;
  segment: "Developer" | "SMB" | "Enterprise" | "Strategic";
  estimatedArr: number;
  activeModules: string[];
  walletCount: number;
  monthlyApiCalls: number;
  activeChainCount: number;
  chains: string[];
  healthScore: number;
  churnRisk: "Low" | "Medium" | "High" | "Critical";
  lastProductActivity: string; // ISO 8601 date string
  icpTier: "A" | "B" | "C";
}

export const accounts: Account[] = [
  // ── Remittance Fintechs ───────────────────────────────────────────────────

  {
    name: "Ruvo",
    domain: "ruvo.com.br",
    industry: "Remittance Fintech",
    country: "Brazil",
    segment: "SMB",
    estimatedArr: 45_000,
    activeModules: ["Embedded Wallets", "Stablecoin Orchestration"],
    walletCount: 3_200,
    monthlyApiCalls: 180_000,
    activeChainCount: 2,
    chains: ["Ethereum", "Polygon"],
    healthScore: 72,
    churnRisk: "Medium",
    lastProductActivity: "2026-03-18",
    icpTier: "B",
  },
  {
    name: "Kasi",
    domain: "kasi.finance",
    industry: "Remittance Fintech",
    country: "Kenya",
    segment: "SMB",
    estimatedArr: 62_000,
    activeModules: ["Embedded Wallets", "Stablecoin Orchestration", "Offramp"],
    walletCount: 8_500,
    monthlyApiCalls: 320_000,
    activeChainCount: 2,
    chains: ["Solana", "Polygon"],
    healthScore: 81,
    churnRisk: "Low",
    lastProductActivity: "2026-03-25",
    icpTier: "A",
  },
  {
    name: "Cacao Finance",
    domain: "cacaofinance.com",
    industry: "Remittance Fintech",
    country: "Brazil",
    segment: "Enterprise",
    estimatedArr: 180_000,
    activeModules: [
      "Embedded Wallets",
      "Stablecoin Orchestration",
      "Onramp",
      "Offramp",
    ],
    walletCount: 22_000,
    monthlyApiCalls: 750_000,
    activeChainCount: 3,
    chains: ["Ethereum", "Polygon", "Base"],
    healthScore: 88,
    churnRisk: "Low",
    lastProductActivity: "2026-03-29",
    icpTier: "A",
  },
  {
    name: "SendCrypto",
    domain: "sendcrypto.io",
    industry: "Remittance Fintech",
    country: "Singapore",
    segment: "SMB",
    estimatedArr: 38_000,
    activeModules: ["Embedded Wallets", "Onramp"],
    walletCount: 5_100,
    monthlyApiCalls: 210_000,
    activeChainCount: 2,
    chains: ["Polygon", "Solana"],
    healthScore: 65,
    churnRisk: "Medium",
    lastProductActivity: "2026-02-14",
    icpTier: "B",
  },
  {
    name: "FlowRemit",
    domain: "flowremit.mx",
    industry: "Remittance Fintech",
    country: "Mexico",
    segment: "SMB",
    estimatedArr: 29_000,
    activeModules: ["Embedded Wallets", "Stablecoin Orchestration"],
    walletCount: 2_800,
    monthlyApiCalls: 95_000,
    activeChainCount: 1,
    chains: ["Polygon"],
    healthScore: 58,
    churnRisk: "High",
    lastProductActivity: "2026-01-22",
    icpTier: "B",
  },

  // ── Neobanks ──────────────────────────────────────────────────────────────

  {
    name: "Wirex",
    domain: "wirex.app",
    industry: "Neobank",
    country: "United Kingdom",
    segment: "Enterprise",
    estimatedArr: 320_000,
    activeModules: [
      "Embedded Wallets",
      "Treasury",
      "Stablecoin Orchestration",
      "Onramp",
      "Offramp",
    ],
    walletCount: 85_000,
    monthlyApiCalls: 2_400_000,
    activeChainCount: 4,
    chains: ["Ethereum", "Polygon", "Bitcoin", "Solana"],
    healthScore: 91,
    churnRisk: "Low",
    lastProductActivity: "2026-03-31",
    icpTier: "A",
  },
  {
    name: "Colb Finance",
    domain: "colbfinance.com",
    industry: "Neobank",
    country: "Colombia",
    segment: "SMB",
    estimatedArr: 55_000,
    activeModules: ["Embedded Wallets", "Tokenization"],
    walletCount: 4_200,
    monthlyApiCalls: 145_000,
    activeChainCount: 2,
    chains: ["Ethereum", "Polygon"],
    healthScore: 74,
    churnRisk: "Medium",
    lastProductActivity: "2026-03-10",
    icpTier: "B",
  },
  {
    name: "NeoVault",
    domain: "neovault.eu",
    industry: "Neobank",
    country: "Germany",
    segment: "Enterprise",
    estimatedArr: 260_000,
    activeModules: [
      "Embedded Wallets",
      "Treasury",
      "Onramp",
      "Offramp",
      "Stablecoin Orchestration",
    ],
    walletCount: 48_000,
    monthlyApiCalls: 1_850_000,
    activeChainCount: 4,
    chains: ["Ethereum", "Polygon", "Base", "Arbitrum"],
    healthScore: 85,
    churnRisk: "Low",
    lastProductActivity: "2026-03-27",
    icpTier: "A",
  },
  {
    name: "StackBank",
    domain: "stackbank.com",
    industry: "Neobank",
    country: "United States",
    segment: "Enterprise",
    estimatedArr: 195_000,
    activeModules: ["Embedded Wallets", "Stablecoin Orchestration", "Onramp"],
    walletCount: 31_000,
    monthlyApiCalls: 980_000,
    activeChainCount: 3,
    chains: ["Ethereum", "Solana", "Base"],
    healthScore: 79,
    churnRisk: "Low",
    lastProductActivity: "2026-03-20",
    icpTier: "A",
  },

  // ── Payroll Platforms ─────────────────────────────────────────────────────

  {
    name: "Toku",
    domain: "toku.com",
    industry: "Payroll Platform",
    country: "United States",
    segment: "Strategic",
    estimatedArr: 1_200_000,
    activeModules: [
      "Embedded Wallets",
      "Treasury",
      "Stablecoin Orchestration",
      "Onramp",
      "Offramp",
      "Agentic Payments",
    ],
    walletCount: 125_000,
    monthlyApiCalls: 5_200_000,
    activeChainCount: 5,
    chains: ["Ethereum", "Polygon", "Solana", "Base", "Arbitrum"],
    healthScore: 94,
    churnRisk: "Low",
    lastProductActivity: "2026-03-31",
    icpTier: "A",
  },
  {
    name: "PayStream",
    domain: "paystream.io",
    industry: "Payroll Platform",
    country: "United States",
    segment: "SMB",
    estimatedArr: 78_000,
    activeModules: [
      "Embedded Wallets",
      "Stablecoin Orchestration",
      "Offramp",
    ],
    walletCount: 12_500,
    monthlyApiCalls: 410_000,
    activeChainCount: 2,
    chains: ["Polygon", "Solana"],
    healthScore: 76,
    churnRisk: "Low",
    lastProductActivity: "2026-03-15",
    icpTier: "B",
  },
  {
    name: "GlobalPay",
    domain: "globalpay.network",
    industry: "Payroll Platform",
    country: "United Kingdom",
    segment: "Strategic",
    estimatedArr: 850_000,
    activeModules: [
      "Embedded Wallets",
      "Treasury",
      "Stablecoin Orchestration",
      "Onramp",
      "Offramp",
    ],
    walletCount: 95_000,
    monthlyApiCalls: 3_800_000,
    activeChainCount: 6,
    chains: ["Ethereum", "Polygon", "Solana", "Base", "Arbitrum", "Optimism"],
    healthScore: 89,
    churnRisk: "Low",
    lastProductActivity: "2026-03-28",
    icpTier: "A",
  },

  // ── Enterprise ────────────────────────────────────────────────────────────

  {
    name: "MoneyGram",
    domain: "moneygram.com",
    industry: "Money Transfer",
    country: "United States",
    segment: "Strategic",
    estimatedArr: 3_500_000,
    activeModules: [
      "Embedded Wallets",
      "Treasury",
      "Stablecoin Orchestration",
      "Onramp",
      "Offramp",
      "Agentic Payments",
    ],
    walletCount: 450_000,
    monthlyApiCalls: 18_500_000,
    activeChainCount: 6,
    chains: ["Ethereum", "Polygon", "Solana", "Base", "Arbitrum", "Stellar"],
    healthScore: 96,
    churnRisk: "Low",
    lastProductActivity: "2026-03-31",
    icpTier: "A",
  },
  {
    name: "Western Union",
    domain: "westernunion.com",
    industry: "Money Transfer",
    country: "United States",
    segment: "Strategic",
    estimatedArr: 4_200_000,
    activeModules: [
      "Embedded Wallets",
      "Treasury",
      "Stablecoin Orchestration",
      "Onramp",
      "Offramp",
      "Tokenization",
    ],
    walletCount: 620_000,
    monthlyApiCalls: 24_000_000,
    activeChainCount: 4,
    chains: ["Solana", "Ethereum", "Polygon", "Stellar"],
    healthScore: 95,
    churnRisk: "Low",
    lastProductActivity: "2026-03-30",
    icpTier: "A",
  },
  {
    name: "Santander",
    domain: "santander.com",
    industry: "Banking",
    country: "Spain",
    segment: "Strategic",
    estimatedArr: 2_800_000,
    activeModules: [
      "Embedded Wallets",
      "Treasury",
      "Tokenization",
      "Stablecoin Orchestration",
      "Onramp",
      "Offramp",
    ],
    walletCount: 380_000,
    monthlyApiCalls: 15_200_000,
    activeChainCount: 3,
    chains: ["Ethereum", "Polygon", "Base"],
    healthScore: 92,
    churnRisk: "Low",
    lastProductActivity: "2026-03-29",
    icpTier: "A",
  },
  {
    name: "Mastercard",
    domain: "mastercard.com",
    industry: "Payments Infrastructure",
    country: "United States",
    segment: "Strategic",
    estimatedArr: 5_000_000,
    activeModules: [
      "Embedded Wallets",
      "Treasury",
      "Tokenization",
      "Stablecoin Orchestration",
      "Onramp",
      "Offramp",
      "Agentic Payments",
    ],
    walletCount: 1_200_000,
    monthlyApiCalls: 48_000_000,
    activeChainCount: 6,
    chains: ["Ethereum", "Polygon", "Solana", "Base", "Arbitrum", "Avalanche"],
    healthScore: 98,
    churnRisk: "Low",
    lastProductActivity: "2026-03-31",
    icpTier: "A",
  },

  // ── Gaming / NFT ──────────────────────────────────────────────────────────

  {
    name: "PixelVault",
    domain: "pixelvault.com",
    industry: "Gaming / NFT",
    country: "United States",
    segment: "Developer",
    estimatedArr: 18_000,
    activeModules: ["Embedded Wallets", "Tokenization"],
    walletCount: 8_200,
    monthlyApiCalls: 285_000,
    activeChainCount: 2,
    chains: ["Ethereum", "Polygon"],
    healthScore: 62,
    churnRisk: "Medium",
    lastProductActivity: "2026-02-28",
    icpTier: "C",
  },
  {
    name: "ChainQuest",
    domain: "chainquest.gg",
    industry: "Gaming / NFT",
    country: "United States",
    segment: "Developer",
    estimatedArr: 8_500,
    activeModules: ["Embedded Wallets"],
    walletCount: 3_100,
    monthlyApiCalls: 92_000,
    activeChainCount: 1,
    chains: ["Polygon"],
    healthScore: 45,
    churnRisk: "High",
    lastProductActivity: "2026-01-15",
    icpTier: "C",
  },
  {
    name: "ArtBlock",
    domain: "artblock.io",
    industry: "Gaming / NFT",
    country: "United States",
    segment: "SMB",
    estimatedArr: 42_000,
    activeModules: ["Embedded Wallets", "Tokenization", "Onramp"],
    walletCount: 15_000,
    monthlyApiCalls: 380_000,
    activeChainCount: 2,
    chains: ["Ethereum", "Base"],
    healthScore: 71,
    churnRisk: "Medium",
    lastProductActivity: "2026-03-05",
    icpTier: "B",
  },
  {
    name: "MetaLoot",
    domain: "metaloot.gg",
    industry: "Gaming / NFT",
    country: "United States",
    segment: "Developer",
    estimatedArr: 12_000,
    activeModules: ["Embedded Wallets", "Agentic Payments"],
    walletCount: 4_800,
    monthlyApiCalls: 142_000,
    activeChainCount: 2,
    chains: ["Solana", "Polygon"],
    healthScore: 55,
    churnRisk: "High",
    lastProductActivity: "2026-01-08",
    icpTier: "C",
  },
];
